package com.pengxh.autodingding.greendao;

import com.pengxh.autodingding.bean.DailyTaskBean;
import com.pengxh.autodingding.bean.NotificationBean;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dailyTaskBeanDaoConfig;
    private final DaoConfig notificationBeanDaoConfig;

    private final DailyTaskBeanDao dailyTaskBeanDao;
    private final NotificationBeanDao notificationBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dailyTaskBeanDaoConfig = daoConfigMap.get(DailyTaskBeanDao.class).clone();
        dailyTaskBeanDaoConfig.initIdentityScope(type);

        notificationBeanDaoConfig = daoConfigMap.get(NotificationBeanDao.class).clone();
        notificationBeanDaoConfig.initIdentityScope(type);

        dailyTaskBeanDao = new DailyTaskBeanDao(dailyTaskBeanDaoConfig, this);
        notificationBeanDao = new NotificationBeanDao(notificationBeanDaoConfig, this);

        registerDao(DailyTaskBean.class, dailyTaskBeanDao);
        registerDao(NotificationBean.class, notificationBeanDao);
    }
    
    public void clear() {
        dailyTaskBeanDaoConfig.clearIdentityScope();
        notificationBeanDaoConfig.clearIdentityScope();
    }

    public DailyTaskBeanDao getDailyTaskBeanDao() {
        return dailyTaskBeanDao;
    }

    public NotificationBeanDao getNotificationBeanDao() {
        return notificationBeanDao;
    }

}
